// 放入公共常量
export const SET_USER_STATUS = 'setUserStatus'

export const SET_VIEW_NAME = 'setViewName'
export const GET_USER_INFO = 'getUserInfo'
export const GET_ROLE_LIST = 'getRoleList'
export const GET_ROUTER_LIST = 'getRouterList'
export const GET_TABLE_DATA = 'getTableData'
export const DELETE_TABLE_DATA = 'deleteTableData'
export const SET_PAGE_DATA = 'setPageData'
export const POP_TABLE_DATA = 'popTableData'
export const POP_ALL_TABLE_DATA = 'popAllTableData'
// export const POP_FLOOR_TABLE_DATA = 'popFloorTableData'
// export const POP_ALL_FLOOR_TABLE_DATA = 'popAllFloorTableData'
export const ADD_NEW_FLOOR_TABLE_DATA = 'addNewFloorTableData'
export const SET_FLOOR_INFO_DATA = 'setFloorInfoData'
export const ADD_FLOOR_MANAGER_INFO = 'addFloorManagerInfo'
export const SET_HOS_INFO_DATA = 'setHosInfoData'
export const CHANGE_USER_INFO = 'changeUserInfo'
export const CHANGE_USER_IMG = 'changeUserImg'
export const CHANGE_USER_PHONE = 'changeUserPhone'
export const CHANGE_USER_EMAIL = 'changeUserEmail'
export const CHANGE_INFO_TIME = 'changeInfoTime'
